name: 'Delete Loft Space'
description: 'GitHub Action to delete a Loft Space'
author: loft.sh
inputs:
  name:
    required: true
    description: 'The name of the space to delete'
  cluster:
    required: false
    description: 'The cluster on which to delete the space (if there are multiple spaces with the same name across multiple clusters)'
  project:
    required: false
    description: "The project to use"
runs:
  using: 'node12'
  main: 'dist/index.js'
